# Imagem base Node.js
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o código fonte
COPY . .

# Expõe a porta do servidor de desenvolvimento
EXPOSE 3000

# Inicia o servidor de desenvolvimento
CMD ["npm", "start"]