version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=sua_chave_secreta_aqui
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dev_class
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: dev_class_db
    environment:
      POSTGRES_DB: dev_class
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: